export default {
  /* App assets */
  logo: require('src/assets/Images/logo.jpg'),
  Premier_League: require('src/assets/Images/Premier_League.jpg'),
  player: require('src/assets/Images/player.png'),
  /* Club logo */
  Arsenal: require('src/assets/Images/Arsenal.png'),
  Manchester_United: require('src/assets/Images/Manchester_United.png'),
  Newcastle_United: require('src/assets/Images/Newcastle_United.png'),
  Tottenham_Hotspur: require('src/assets/Images/Tottenham_Hotspur.png'),
  Aston_Villa: require('src/assets/Images/Aston_Villa.png'),
  Chelsea: require('src/assets/Images/Chelsea.png'),
  Everton: require('src/assets/Images/Everton.png'),
  Leicester_City: require('src/assets/Images/Leicester_City.png'),
  Liverpool: require('src/assets/Images/Liverpool.png'),
  West_Ham_United: require('src/assets/Images/West_Ham_United.png'),
  Brentford: require('src/assets/Images/Brentford.png'),
  Southampton: require('src/assets/Images/Southampton.png'),
  Brighton_and_Hove_Albion: require('src/assets/Images/Brighton_and_Hove_Albion.png'),
  Burnley: require('src/assets/Images/Burnley.png'),
  Watford: require('src/assets/Images/Watford.png'),
  Crystal_Palace: require('src/assets/Images/Crystal_Palace.png'),
  Manchester_City: require('src/assets/Images/Manchester_City.png'),
  Wolverhampton_Wanderers: require('src/assets/Images/Wolverhampton_Wanderers.png'),
  Norwich_City: require('src/assets/Images/Norwich_City.png'),
  Leeds_United: require('src/assets/Images/Leeds_United.png'),
  /* Stadium background */
  Amex_Stadium: require('src/assets/Images/Amex_Stadium.jpg'),
  Brentford_Community_Stadium: require('src/assets/Images/Brentford_Community_Stadium.jpg'),
  Emirates_Stadium: require('src/assets/Images/Emirates_Stadium.jpg'),
  Selhurst_Park: require('src/assets/Images/Selhurst_Park.jpg'),
  Stamford_Bridge: require('src/assets/Images/Stamford_Bridge.jpg'),
  Turf_Moor: require('src/assets/Images/Turf_Moor.jpg'),
  Villa_Park: require('src/assets/Images/Villa_Park.jpg'),
  Anfield: require('src/assets/Images/Anfield.jpg'),
  Elland_Road: require('src/assets/Images/Elland_Road.jpg'),
  Etihad_Stadium: require('src/assets/Images/Etihad_Stadium.jpg'),
  Goodison_Park: require('src/assets/Images/Goodison_Park.jpg'),
  King_Power_Stadium: require('src/assets/Images/King_Power_Stadium.jpg'),
  Old_Trafford: require('src/assets/Images/Old_Trafford.jpg'),
  St_James_Park: require('src/assets/Images/St_James_Park.jpg'),
  Carrow_Road: require('src/assets/Images/Carrow_Road.jpg'),
  St_Marys_Stadium: require('src/assets/Images/St_Marys_Stadium.jpg'),
  Tottenham_Hotspur_Stadium: require('src/assets/Images/Tottenham_Hotspur_Stadium.jpg'),
  Vicarage_Road: require('src/assets/Images/Vicarage_Road.jpg'),
  London_Stadium: require('src/assets/Images/London_Stadium.jpg'),
  Molineux_Stadium: require('src/assets/Images/Molineux_Stadium.jpg'),
};
