export default {
  logo: require('src/assets/Images/logo.jpg'),
  Arsenal: require('src/assets/Images/Arsenal.png'),
  Manchester_United: require('src/assets/Images/Manchester_United.png'),
  Newcastle_United: require('src/assets/Images/Newcastle_United.png'),
  Tottenham_Hotspur: require('src/assets/Images/Tottenham_Hotspur.png'),
  Aston_Villa: require('src/assets/Images/Aston_Villa.png'),
  Chelsea: require('src/assets/Images/Chelsea.png'),
  Everton: require('src/assets/Images/Everton.png'),
  Leicester_City: require('src/assets/Images/Leicester_City.png'),
  Liverpool: require('src/assets/Images/Liverpool.png'),
  West_Ham_United: require('src/assets/Images/West_Ham_United.png'),
  Brentford: require('src/assets/Images/Brentford.png'),
  Southampton: require('src/assets/Images/Southampton.png'),
  Brighton_and_Hove_Albion: require('src/assets/Images/Brighton_and_Hove_Albion.png'),
  Burnley: require('src/assets/Images/Burnley.png'),
  Watford: require('src/assets/Images/Watford.png'),
  Crystal_Palace: require('src/assets/Images/Crystal_Palace.png'),
  Manchester_City: require('src/assets/Images/Manchester_City.png'),
  Wolverhampton_Wanderers: require('src/assets/Images/Wolverhampton_Wanderers.png'),
  Norwich_City: require('src/assets/Images/Norwich_City.png'),
  Leeds_United: require('src/assets/Images/Leeds_United.png'),
};
